apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../../base/applications/lotus-stats

# patchesStrategicMerge:
#   - lotus-stats-helmrelease-patch.yaml

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: lotus-stats-network-values
