image:
  tag: v1.23.3 # {"$imagepolicy": "ntwk-mainnet:lotus-latest-release:tag"}
prometheusOperatorServiceMonitor: true
resources:
  requests:
    memory: 32Gi
    cpu: 4
  limits:
    memory: 48Gi
    cpu: 6
importSnapshot:
  enabled: true
  strategy: url
persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "2000Gi"
daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]
  [Chainstore]
    EnableSplitstore = true
  [Chainstore.Splitstore]
    ColdStoreType = "discard"
daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1
disputer:
  enabled: true
  walletAddr: f1xfr2bh23j2s7rmvwxx4linma4luxqxpyrfax5da
  maxFee: "1"
  env:
    - name: GOLOG_LOG_FMT
      value: json
additionalLabels:
  network: mainnet
nodeSelector:
  "node.kubernetes.io/instance-type": "r5.2xlarge"
