image:
  tag: v1.22.0 # {"$imagepolicy": "ntwk-mainnet:lotus-latest-release:tag"}
prometheusOperatorServiceMonitor: true
resources:
  requests:
    memory: 32Gi
    cpu: 4
  limits:
    memory: 48Gi
    cpu: 6
importSnapshot:
  enabled: true
  strategy: url
persistence:
  datastore:
    enabled: true
    easyReset: true
    size: "2000Gi"
daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1
disputer:
  enabled: true
  walletAddr: f1xfr2bh23j2s7rmvwxx4linma4luxqxpyrfax5da
  # maxFee:
  env:
    - name: GOLOG_LOG_FMT
      value: json
additionalLabels:
  network: mainnet
nodeSelector:
  "node.kubernetes.io/instance-type": "r5.2xlarge"
