# calibration

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-calibnet-sentinel
  name: ntwk-calibnet-sentinel-edit
subjects:
  - kind: Group
    name: ntwk-calibnet-sentinel-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-calibnet-sentinel
  name: ntwk-calibnet-sentinel-view
subjects:
  - kind: Group
    name: ntwk-calibnet-sentinel-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-calibnet-sentinel
  name: ntwk-calibnet-sentinel-exec
subjects:
  - kind: Group
    name: ntwk-calibnet-sentinel-exec
roleRef:
  kind: Role
  name: ntwk-calibnet-sentinel-exec
  apiGroup: rbac.authorization.k8s.io


# mainnet

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-bootstrap-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-view
subjects:
  - kind: Group
    name: ntwk-mainnet-bootstrap-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-bootstrap-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-bootstrap-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-dealbot
  name: ntwk-mainnet-dealbot-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-dealbot-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-dealbot
  name: ntwk-mainnet-dealbot-view
subjects:
  - kind: Group
    name: ntwk-mainnet-dealbot-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-dealbot
  name: ntwk-mainnet-dealbot-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-dealbot-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-dealbot-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-disputer-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-view
subjects:
  - kind: Group
    name: ntwk-mainnet-disputer-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-disputer-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-disputer-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-fullnode
  name: ntwk-mainnet-fullnode-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-fullnode-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-fullnode
  name: ntwk-mainnet-fullnode-view
subjects:
  - kind: Group
    name: ntwk-mainnet-fullnode-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-fullnode
  name: ntwk-mainnet-fullnode-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-fullnode-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-fullnode-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-sentinel
  name: ntwk-mainnet-sentinel-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-sentinel-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-sentinel
  name: ntwk-mainnet-sentinel-view
subjects:
  - kind: Group
    name: ntwk-mainnet-sentinel-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-sentinel
  name: ntwk-mainnet-sentinel-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-sentinel-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-sentinel-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-stats
  name: ntwk-mainnet-stats-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-stats-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-stats
  name: ntwk-mainnet-stats-view
subjects:
  - kind: Group
    name: ntwk-mainnet-stats-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-stats
  name: ntwk-mainnet-stats-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-stats-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-stats-exec
  apiGroup: rbac.authorization.k8s.io


# fluxcd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: default
  name: fluxcd-is-master
subjects:
  - kind: ServiceAccount
    namespace: default
    name: fluxcd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
