---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proof-params-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  storageClassName: csi-cephfs
