name: "Lotus Ansible Upgrade"
description: "Composite action to upgrade Lotus using Ansible"
inputs:
  deploy_network:
    description: "Deploy network"
    required: true
  build_flags:
    description: "Build flags"
    required: false
    default: "-f"
  check:
    description: "Check"
    required: false
    default: "true"
  DOCKERHUB_USERNAME:
    description: "Dockerhub Username"
    required: true
  DOCKERHUB_PASSWORD:
    description: "Dockerhub Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Check Env
      shell: bash
      run: |
        if [ -z "$GOPATH" ]; then
          echo "GOPATH is not set"
          exit 1
        fi
        if [ -z "$LOTUSROOT" ]; then
          echo "LOTUSROOT is not set"
          exit 1
        fi

    - name: Ansible Upgrade ${{ inputs.deploy_network }}
      shell: bash
      working-directory: ansible
      env:
        DEPLOY_NETWORK: ${{ inputs.deploy_network }}
        BUILD_FLAGS: ${{ inputs.build_flags }}
        CHECK: ${{ inputs.check }}
      run: |
        args=(
          "-n" "${DEPLOY_NETWORK}"
          "-s" "${LOTUSROOT}"
          "-b" "${BUILD_FLAGS}"
          "--verbose"
        )
        [ "${CHECK}" == "true" ] && args+=("--check")

        export TERM=xterm
        unset GOPATH
        ./upgrade_fildev_network_binaries.bash "${args[@]}"

    - name: Remove Faucet Maintenance
      if: ${{ inputs.check == 'false' }}
      shell: bash
      working-directory: ansible
      env:
        DEPLOY_NETWORK: ${{ inputs.deploy_network }}
      run: |
        ansible -i inventories/${DEPLOY_NETWORK}/hosts.yml -b -m file -a 'state=link src=/etc/nginx/sites-available/faucet.conf dest=/etc/nginx/sites-enabled/50-faucet.conf' faucet

    - name: Restart Machines
      if: ${{ inputs.check == 'false' }}
      shell: bash
      working-directory: ansible
      env:
        DEPLOY_NETWORK: ${{ inputs.deploy_network }}
      run: |
        ansible -i inventories/${DEPLOY_NETWORK}/hosts.yml -b -m reboot all
