apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/lotus-stats
- lotus-stats-secret.yaml

namePrefix: lotus-stats-

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: lotus-stats-values
