data:
    influx_hostname: ENC[AES256_GCM,data:tI/YHJtWk0ffuN3x0MEtdpEpeeE3fO2Kjo9Oyx7w1DJFEP85DST/T+CkPy1DucXqEahL45dwbxTrkUTL42RDFx+EDvg=,iv:c8VEWS9ppvLUZ6UpC2sqDxGuEOBgnoColpTdSNcU2Xc=,tag:kkmH5LHR9xNt0c0MYHjV/g==,type:str]
    influx_password: ENC[AES256_GCM,data:MVqEUMrpSH7ZPgSY5iFfcezOx6uWyKLDC2rjdAcoTBU=,iv:IJRa7EK5DWSy0B1S7FK3TrAFUo1w0dQ5A6cb2qDP1mA=,tag:Gz5LMKjfPe9DA+LxZg9qhg==,type:str]
    influx_username: ENC[AES256_GCM,data:fJgxhNnPQFY=,iv:qw3BK4BDNo7Qn1wJ8eVyvTSXG12f1Q+Vu5n5qaIylK0=,tag:MSEHfPQEC2v0YjbbyQ+/lQ==,type:str]
kind: Secret
metadata:
    name: lotus-stats
    namespace: ntwk-mainnet
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-19T16:49:05Z"
    mac: ENC[AES256_GCM,data:sVEJQLEFmudwnoBhulAF5b0w8xZw0N+H+gYoD24Hy+uFCyP0Z+gY4QTAxEJfdKJ/vLZjhcxWEuZ5DNvzW2I8ys1ZYO0MCGR+bj9S+f4rIWWKQNbw/dqi5MEFbGDd0et1ngxbrkGr3/cxEJkZcy4Rn6EWhv61w+UQ1pJGSVnSCpE=,iv:lY6CFfK6mQFomKPE9mEnFHs8sBbVgCXCHXuOdGFACFw=,tag:eK0zcsvT02v6aFYkTOJCNg==,type:str]
    pgp:
        - created_at: "2023-01-19T16:49:04Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA10BBd9Ja1tnARAAmVV+rcgo8vqHDMLtqToCGefLRfs2X0IhIX4nrt/nsGaO
            dVAQnuQADNPEApb2LtPLS0+r+BJyEs941yRyC6IiEQCYPWxFm8/B7e9/q/7LyL1C
            /+wbTR5vbEeqV9Q9+edwrETZ8gJ0GO6YGyDixIO45ZMynstpevVhMpXW3ImlIIHB
            dz8DTpxaQ2VXWOMYmMnLL56pd/qD/24fKvJ07c9v+E9NcmhSrrBVL5xYAQLOw1NC
            UbjkCaYUcdONoUyU/XZdUSHnDH7ah62juxEi3VqO1czaU7Q14UlGxNOzFXhBUWVY
            ZiuzmUmWsbMeC5iI7Vi2ycJ5QGIHbREdJZjtiwa/yOorPz2/B1tjXwpVKuUKN/wd
            g+h+PRBmtkMiFX3pE44IjiaKA11oC2jJ3PYV8tVO1Dnl5i/WNNG4LKNZdSBiYMSM
            4tgUKHxiqbqoES3svPJ7BaL3nZyECdCD39Xc5dls6XQWsSLBAQ2mM4cISapBRb4N
            CZ4Ugv3tPjn+DBk6QJTdOaW8OGhw788CUAi2FueMEB2kUIacJPjQzjU/MEAnpOqU
            LV7Yy3ghkGgk9hY1WM0iG4fZcqUTww47FLwFN05fgimPUCU2If01MUAQgMunK7wh
            aompRM5sp0wBZr4ceDrClw6ZXJVJGwXH22chJDPqlH6KfD/raS3iKcJOsxobM6/S
            XgEoNhSwwg5cY0JxTmk8Uaa/uVwWfSPyhkF5tCOu6rLnmYbXb7+KYilb2OgmmoEm
            6tBrLKakH95kDT4vuU9CtOUjjjL0jNEZkv9l6wc/Vqw4hGrup0ZPqj1zlroKyjE=
            =bp+6
            -----END PGP MESSAGE-----
          fp: 82B6F581AA9BAC43F18A9D2E8F13E77F0EF448C4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
