# you may need to change this to a recent epoch if there's been a prolonged stats outage
height: "0"
#lotusApiInfo: /dns/node-0-fullnode-lotus-daemon/tcp/1234
lotusApiInfo: /dns/api-chain-love-gateway-lotus-gateway-0/ws

influxDatabase: chainstats-ntwk-mainnet
influxSecrets: lotus-stats-lotus-stats
