---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chain-snapshot-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: csi-cephfs
