secrets:
  jwt:
    enabled: true
    secretName: lightweight-snapshot-node-jwt-secret
image:
  tag: v1.25.1-calibnet # {"$imagepolicy": "ntwk-calibrationnet:lotus-calibnet-latest-rc:tag"}
importSnapshot:
  enabled: true
  # Attempt to fix a fork by reverting to a pre-upgrade snapshot
  url: https://pub-f851d666b9a54f60bd93202926618941.r2.dev/minimal/1070160_2023_11_08T08_13_00Z.car.zst
  strategy: "url"
