---
all:
  children:
    packet:
      vars:
        ansible_user: root
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
        kubernetes_join_command_extra_opts: "--skip-phases=preflight"
      children:
        k8s_master:
          vars:
            kubernetes_role: "master"
            mdadm_arrays:
              - name: 'md0'
                devices:
                  - '/dev/sdb'
                  - '/dev/sdc'
                filesystem: 'ext4'
                filesystem_opts: ''
                level: '0'
                mountpoint: '/mnt/md0'
                state: 'present'
                opts: 'noatime'
          hosts:
            147.75.54.183:
              vlan1_ip: 192.168.1.1
        k8s_worker:
          vars:
            kubernetes_role: "node"
          children:
            miner:
              hosts:
                139.178.82.207:
                  vlan1_ip: 192.168.1.2
            generic:
              hosts:
                139.178.82.15:
                  vlan1_ip: 192.168.1.254
            monitoring:
              hosts:
                139.178.85.167:
                  vlan1_ip: 192.168.1.10
            seal_worker:
              hosts:
                139.178.82.173:
                  vlan1_ip: 192.168.1.11
                  swap_device: /dev/sdc
                  mdadm_arrays:
                    - name: 'md0'
                      devices:
                        - '/dev/sda'
                        - '/dev/sdb'
                      filesystem: 'ext4'
                      filesystem_opts: ''
                      level: '0'
                      mountpoint: '/mnt/md0'
                      state: 'present'
                      opts: 'noatime'
                139.178.82.45:
                  vlan1_ip: 192.168.1.13
                  swap_device: /dev/sdc
                  mdadm_arrays:
                    - name: 'md0'
                      devices:
                        - '/dev/sda'
                        - '/dev/sdb'
                      filesystem: 'ext4'
                      filesystem_opts: ''
                      level: '0'
                      mountpoint: '/mnt/md0'
                      state: 'present'
                      opts: 'noatime'
            seal_worker_gpu:
              hosts:
                139.178.85.79:
                  vlan1_ip: 192.168.1.12
                  mdadm_arrays:
                    - name: 'md0'
                      devices:
                        - '/dev/sdb'
                        - '/dev/sdc'
                      filesystem: 'ext4'
                      filesystem_opts: ''
                      level: '0'
                      mountpoint: '/mnt/md0'
                      state: 'present'
                      opts: 'noatime'
            ceph:
              vars:
                vlan1_gw_enabled: true
              children:
                ceph_mon:
                  hosts:
                    192.168.1.7:
                      vlan1_ip: 192.168.1.7
                      vlan2_ip: 192.168.2.5
                    192.168.1.6:
                      vlan1_ip: 192.168.1.6
                      vlan2_ip: 192.168.2.4
                    192.168.1.8:
                      vlan1_ip: 192.168.1.8
                      vlan2_ip: 192.168.2.6
                ceph_osd:
                  vars:
                    mdadm_arrays:
                      - name: 'md0'
                        devices:
                          - '/dev/nvme0n1'
                          - '/dev/nvme1n1'
                        filesystem: 'ext4'
                        filesystem_opts: ''
                        level: '0'
                        state: 'present'
                        opts: 'noatime'
                  hosts:
                    192.168.1.5:
                      vlan1_ip: 192.168.1.5
                      vlan2_ip: 192.168.2.3
                    192.168.1.3:
                      vlan1_ip: 192.168.1.3
                      vlan2_ip: 192.168.2.1
                    192.168.1.4:
                      vlan1_ip: 192.168.1.4
                      vlan2_ip: 192.168.2.2
        # this is seperated out because these servers are fully in L2 networking mode
        # not reachable by management IP
