secrets:
  libp2p:
    enabled: true
    secretName: fullnode-0-libp2p-secrets
    libp2p_key: libp2p-host
  jwt:
    enabled: true
    secretName: fullnode-0-jwt-secrets

importSnapshot:
  enabled: false

nodeSelector:
  "node.kubernetes.io/instance-type": "r5b.8xlarge"

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]
  [Chainstore]
    EnableSplitstore = false

# Set LOTUS_MIGRATION_MAX_WORKER_COUNT for full nodes to prevent
# OOM, copy the base envs so we don't unset anything
daemonEnvs:
- name: GOLOG_LOG_FMT
  value: json
- name: GODEBUG
  value: madvdontneed=1
- name: DISABLE_PRE_MIGRATIONS
  value: "1"
- name: LOTUS_MIGRATION_MAX_WORKER_COUNT
  value: "8"
