---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: butterflynet-lotus
  namespace: ntwk-butterflynet
spec:
  interval: 5m
  image: docker.io/filecoin/lotus-all-in-one
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: butterflynet-lotus
  namespace: ntwk-butterflynet
spec:
  filterTags:
    # XXX: This may end up  being too liberal since it will match non-semver2 prefixes
    #      but a regex literal matching semver2 is not worth including imho
    pattern: '(?P<hopefully_semver2>.*)-butterflynet'
    extract: '$hopefully_semver2'
  policy:
    semver:
      range: '~1.18.x'
  imageRepositoryRef:
    name: butterflynet-lotus
