---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: calibrationnet-lotus
  namespace: ntwk-calibrationnet
spec:
  interval: 5m
  image: docker.io/travisperson/lotus
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: calibrationnet-lotus
  namespace: ntwk-calibrationnet
spec:
  filterTags:
   pattern: 'calibrationnet-.*'
  policy:
    semver:
      range: calibrationnet-v0.x.x
  imageRepositoryRef:
    name: calibrationnet-lotus

