# Default values for go-filecoin-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
#prometheusOperator:
#  tolerations:
#    - key: "monitoring"
#      operator: "Equal"
#      value: "true"
#      effect: "NoSchedule"
#    - key: "monitoring"
#      operator: "Equal"
#      value: "true"
#      effect: "NoExecute"
#  nodeSelector:
#    monitoring: "true"
#  admissionWebhooks:
#    patch:
#      tolerations:
#        - key: "monitoring"
#          operator: "Equal"
#          value: "true"
#          effect: "NoSchedule"
#        - key: "monitoring"
#          operator: "Equal"
#          value: "true"
#          effect: "NoExecute"
#      nodeSelector:
#        monitoring: "true"
grafana:
  enabled: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: gp2
    accessModes: ["ReadWriteOnce"]
    size: 25Gi
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
      enabled: true
alertmanager:
  #service:
  #  type: LoadBalancer
  #  annotations:
  #    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:657871693752:certificate/468a4a8a-3778-44ad-821f-d788bb2e898d"
  #    external-dns.alpha.kubernetes.io/hostname: fil-alertmanager.kittyhawk.wtf
  #    external-dns.alpha.kubernetes.io/alias: "true"
  #    external-dns.alpha.kubernetes.io/ttl: "60"
  alertmanagerSpec:
    replicas: 1
    retention: 336h
    #externalUrl: https://fil-alertmanager.kittyhawk.wtf
    externalUrl: "http://localhost:3002"
    #containers:
    #  - image: beevelop/nginx-basic-auth
    #    env:
    #      - name: HTPASSWD
    #        value:
    #      - name: FORWARD_PORT
    #        value:
    #tolerations:
    #  - key: "monitoring"
    #    operator: "Equal"
    #    value: "true"
    #    effect: "NoSchedule"
    #  - key: "monitoring"
    #    operator: "Equal"
    #    value: "true"
    #    effect: "NoExecute"
    #nodeSelector:
    #  monitoring: "true"
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: gp2
          resources:
            requests:
              storage: 10Gi
# Filecoin Scraping
prometheus:
  #additionalServiceMonitors:
  #  - selector:
  #      matchLabels:
  #        monitoring: prometheus
  #    endpoints:
  #      - port: prometheus
  #        path: "/metrics"
  #        interval: "30s"
  #    namespaceSelector:
  #      any: true
  #    name: filecoin-daemon
  prometheusSpec:
    replicas: 1
    ruleSelector: {}
    ruleNamespaceSelector: {}
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    retention: 60d
    #tolerations:
    #  - key: "monitoring"
    #    operator: "Equal"
    #    value: "true"
    #    effect: "NoSchedule"
    #  - key: "monitoring"
    #    operator: "Equal"
    #    value: "true"
    #    effect: "NoExecute"
    #nodeSelector:
    #  monitoring: "true"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 250Gi
    #additionalAlertManagerConfigs:
    #alertingEndpoints:
    #additionalScrapeConfigs: |
      #job_name: "go-lotus"
      #basic_auth:
      #  [ username: <string> ]
      #  [ password: <secret> ]
