- name: Ensure lotus group exists
  group:
    name: "{{ lotus_user }}"
    state: present
    gid: "{{ lotus_user_uid }}"
    system: yes

- name: Ensure lotus user exists
  user:
    name: "{{ lotus_user }}"
    state: present
    uid: "{{ lotus_user_uid }}"
    system: yes

- name: Ensure login user is added group
  user:
    name: "{{ ansible_user }}"
    state: present
    append: yes
    groups: "{{ lotus_user }}"
