apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: flux-slack-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:UJmwdFU3sO/iJDqWipFrO1waNHr5Z68co6wI4bLG5spBulM3MPSfXsHYPWPjysaAB84G6OtWBv7requ3OYnGE6drUtgwC2k3pEOeYgj34A==,iv:ebaaAJeRWpTCRNYJocHaQBzBQ1kbfdPxOZuaKUMQnS8=,tag:k2gV+J09fTpfE0lmY+rQUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-02-23T18:46:51Z"
    mac: ENC[AES256_GCM,data:yhFQfNlrvdpDoiTImKwz3IJL1FBUwfkkpTdf5wMunuTxAktNSru1J7znIB/vNqzF4ipN49HUwNVVpcFQtKaewRRieYjhknkvaMSSIdQMEyACYD4Aa7VQLWKLL4YSxd06IMoyGVxZ8Fw2apZuFIaAuMHeym13eYCJQkzSYm4xeEE=,iv:k9KnIQ/xrg3ppq7VrL/XE0hJE9Qt4J6Zgy2ulv4T50A=,tag:PaZ9RwVB0WWA/FvTA2/lZw==,type:str]
    pgp:
        - created_at: "2023-02-23T18:46:51Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4VKzs64RjZOAQ/+KBU17ZGIQFhXUNDp5sEJYTLVQDjsrEkRwT5PijzrhAZC
            YXlG4TZeynB6jxSHCHll/0kT+s6E6FAXvAGzZBv+TTJuiW/tK6YHT7T89Svs2pkt
            dRy/l7Ylkdi0q0Tbru7GRQXvO0Gwb8R9lpLtRSh6tiwhbgJRkDyCIFxlrgcWi3h3
            zRhyU218yas5Ig1A7BlYIOMmlWfZzoDBeB+O/csyCsX8/qTjHMS2cSv0HUjTvLne
            3o+usaf00sRXBQIcgIFn0k71ntMzahL+pjDtdDGhE3fOxF08u1FM/hG2ccO/Rzt9
            5yUjjk7P0mzVciuFNrm01GsgEIlecb3s+gVU7FmDI61KcVGucnRMQuDRDfFRcO+/
            Q3iV6YMu1+k7Am5kbHTOoAYpDS5j9c1m3dH48Q2CEAvg9hfOF+MRIi0SbY0npO4N
            sV8jYTl7yGPpxZvB9DWkAO0TN1AIXw0hdDyF0l77bYZ/vlYn+ZGw7L3x9W48/M+x
            9wptN8LfCnB3VsTWW9Q9IjHZi9IZ0OAWUKp9FG+nH10RwTd0Su9EsGeEBAR8Y8iN
            tgRRdrt6PbVaVdoWPd6Clo+/vyHLYiLyvHdH8tKtkOeeT1EJUbapQ+a+OKgZAXhJ
            wW94bhA/lcYZsgNCroef1TOYBI2DAH7oUB3rsK0W0wYIjA1LcdKuz7d2lIQbOaLS
            XgFlDP94fQQnbyKDsNmbVLZs6/ZgZxwY7yfRr/Jw2tKpivVXlyMnB3WhqBaeqhON
            dGT2PBsRLnFXX/Wkuybt4YQq6gx855yIzm5F/mMw1FCcMYPl3+3/rQcHc5CR1yw=
            =5yiG
            -----END PGP MESSAGE-----
          fp: ECB5849EF1F46A7CE613ADF814E151263DDC1737
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
