- include_tasks: ../../../includes/required_vars.yml
- include_tasks: ../../../includes/lotus_general_runtime_deps.yml

- name: Ensure dependencies are installed
  package:
    name:
      - numactl

- name: Copy lotus-seed binary
  copy:
    src: "{{ lotus_seed_binary_src }}"
    dest: /usr/local/bin/lotus-seed
    owner: root
    group: root
    mode: "0755"
  when: lotus_seed_binary_src is defined

- name: Ensure miner key exists
  copy:
    content: "{{ lotus_seed_miner_wallet_keyinfo }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0600"
    dest: "/tmp/{{ lotus_seed_miner_addr }}.key"

- name: Creating seed workers
  include_tasks: worker.yml
  loop: "{{ lotus_seed_workers }}"

- name: Creating migrate workers
  include_tasks: migrate.yml
  loop: "{{ lotus_seed_migrate }}"
  when: lotus_seed_migrate is defined

- set_fact:
    lotus_seed_filebeat_input:
      paths: "{{ lotus_seed_workers | map(attribute='log_file') | list }}"
      fields:
        type: "lotus-seed"

- set_fact:
    lotus_seed_telegraf_tags:
      miner: "{{ lotus_seed_miner_addr }}"
