apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrelease.yaml

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: volume-snapshotter-common-values

configurations:
  - kustomizeconfig.yaml
