image:
  pullPolicy: Always
  tag: "1.1.1"

indexResolver:
  replicas: 1
  s3Resolver:
    bucket: "filecoin-snapshots-mainnet-production"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access

  loadBalancer:
    enabled: false

snapshots:
  uploads:
    enabled: true
    bucket: "filecoin-snapshots-mainnet-production"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access
  additionalEnv:
  - name: "FCA_CREATE_RETRIEVAL_ENDPOINT_PREFIX"
    value: "https://pub-fd31751bcb69400eb39e694385c19457.r2.dev"
  - name: "FCA_CREATE_PROGRESS_UPDATE"
    value: "60s"
  - name: "FCA_CREATE_NAME_PREFIX"
    value: "minimal/"
  - name: "GOLOG_LOG_FMT"
    value: "json"
  nodes:
  - /dns/lws-node-0-fullnode-lotus-daemon/tcp/1234
  - /dns/lws-node-1-fullnode-lotus-daemon/tcp/1234
  - /dns/lws-node-2-fullnode-lotus-daemon/tcp/1234
  - /dns/lws-node-3-fullnode-lotus-daemon/tcp/1234
  - /dns/lws-node-4-fullnode-lotus-daemon/tcp/1234

  schedule: "*/90 * * * *"

podResets:
  - pod: lws-node-0-fullnode-lotus-0
    schedule: "0 0 * * 1,4"
  - pod: lws-node-1-fullnode-lotus-0
    schedule: "0 0 * * 2,5"
  - pod: lws-node-2-fullnode-lotus-0
    schedule: "0 0 * * 3,6"
  - pod: lws-node-3-fullnode-lotus-0
    schedule: "0 12 * * 4,7"
  - pod: lws-node-4-fullnode-lotus-0
    schedule: "0 12 * * 5,1"
