apiVersion: v1
stringData:
    ACCESS_KEY: ENC[AES256_GCM,data:dx9CitXqxbHaJNUAfvmnM6HZ6aqMFz2ujioNhkKOBMQ=,iv:4DS5MFI8BeMrM55xRWvS4+wQZedL9Op5KxSyGo6OFEI=,tag:OhyyKkQfyolmHot/Liexug==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:eEvzoTAZ6T9HKWq+GG10LfmXy4ApYrC0eIuKlyMkr7MEyyXsjv66379OHqdMN/4J45LP8EPLc8MVrJ1WTuqQig==,iv:e8+fRItxHd8uQKFj5Q7zFZDSoCZE2TRQvn33htcJIA4=,tag:63raOl6rmYII1gm3aWqBlg==,type:str]
kind: Secret
metadata:
    name: r2-access
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-12T14:09:23Z"
    mac: ENC[AES256_GCM,data:EmJqHHwYkPwv6zDikXAA7Jq++XmtHwHgc6ruIcKX0+mXkQFTlDthscmePRp/YW1RC6TWh/PT5LiYH42KdbuWQd903o5NqN0k561Tqd7gLF9P/Gg0fVPfwG0E3L2BWaWnWz4qllzGuu5cnzRHJrz31WkccHImn3VnsN1Fpb4H5xM=,iv:/d1RAe3FujuvOBBk5aLBhx8SUOLaD+o8nAG2WBlCK/4=,tag:I2PGfE1Ic0hxdD5uzPR/rw==,type:str]
    pgp:
        - created_at: "2023-10-12T08:28:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA10BBd9Ja1tnARAArbRaU9pMsWl9rILl5C7sNblVhsRxOtMmbk/CFplbgm3W
            uE2J1NqHj5ETWSj5+K/pmAtsxqpz4Hbwnc0J0tWh5BGKaHiQ5PQQjvUNXZhX8HTs
            cjwA5H3/Bib77P/2uPPN8qYFPQfTtVmdrrG0k8ZpAPlJahRQx9AELH09IVKyEJW8
            qx75rEPnO33bWJQCUCcBTAnWcLUDKPiTGP383F6V9OISTUDL27IQE6rZAcsyATgV
            hL7OQAvto2UrO9cxgQKwN0kGD74cJfGmyr6srbfUS98g0xJrcKfn0kvwD0KYGOEm
            GUaRK+TuzJ4lhd2V7Y5GMOBnWB2v4ZP3Fy9FmAyzo/zAA0itNVwewW3W70irterW
            F2sMHAD0Cogtwe1gCroDw4YqtgnwkX36xGK0e+kdI3iqe475rQWXlYfYSUQjixhZ
            iIjNCmVF7N7sDP0aSA6KGsXA5b05RNxE5a9zan41L/ULJT5cXNhSO5KX2DXBm1O5
            hdn9MxizaPGGcOtO73wwhwAQ0kAR2Yz6z3zHOjvJDaY4lqxzMcJ5JqCkKPJFOJM4
            V4x2VdlTAUp7uZI0l90tytKZ3dI2DpjLRbTheGbNT4bZa7yrMVmnk8FSMKUJp6PS
            ewXA1ZDpcM8xNUCxZs0m+NGZheJi6IU6URKg386sNGeyUQB0fZSnERGz/jG0kj/S
            XgG3yoEy2SNBBw+Zau8dmyQ2dh5zLRhdUNTcaqTQVlesvcQSfwYM4KxZzu+Qy8Mj
            0iaqa2JKmsKNejhO8ZyEGhmaEUI+ofT9soBL1VJBqHdFE+Lh2g6jd2yBpfa9RQc=
            =zRUt
            -----END PGP MESSAGE-----
          fp: 82B6F581AA9BAC43F18A9D2E8F13E77F0EF448C4
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
