apiVersion: v1
data:
    ACCESS_KEY: ENC[AES256_GCM,data:bNCrSWj5DKrk+QbPLj8aUTxqLrm007WkcL74ZD4VmobmjMg2I0wgEa/XQfI=,iv:J+vS68JjZRufDwPQZuY/tNAiJM40XtIsHzkFzSkHIRI=,tag:DxUDJ45BuV12W0w/7B1v6A==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:JUDZ6ysHd2K8k/kA22tmPD+nR5ccFJX6vGiz9WB7e4R20CBWwYC+WldKEivHhoeg5DNLXqu3MGuCSfqApb7OK5K4ITz5/CeEdy9C9y8i67ptoFP1xgxS/w==,iv:XY6n3mo6YIkcGTt5ZcYD/FIiHUFWw8UHaeQEcUxiSHQ=,tag:B9VkLddFuD1j5uyn33oHiA==,type:str]
kind: Secret
metadata:
    name: r2-access
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-12T08:28:03Z"
    mac: ENC[AES256_GCM,data:GN4IvRGGLBlM8/mCH0LDEM2dwgxkHgRAU2/2Qfh5UZGddRUwRKoPiH5xuC0G9vPOvkURY0FEUxLr05aynFdndoc23BaJp9bbrO+GLzaMUhoSWmVw/zB/TiPicI/UdRpofd+m8TRAkzyTWWQJK9UofIaCxQrgi8D2J3vYlYD6lXA=,iv:Nml4z9yVIW7Z1V2eN2z3JAKn94A8BY+TcaMqMv9Td00=,tag:xNk1UUH3u8mm0HYKNd/ycA==,type:str]
    pgp:
        - created_at: "2023-10-12T08:28:03Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA10BBd9Ja1tnARAArbRaU9pMsWl9rILl5C7sNblVhsRxOtMmbk/CFplbgm3W
            uE2J1NqHj5ETWSj5+K/pmAtsxqpz4Hbwnc0J0tWh5BGKaHiQ5PQQjvUNXZhX8HTs
            cjwA5H3/Bib77P/2uPPN8qYFPQfTtVmdrrG0k8ZpAPlJahRQx9AELH09IVKyEJW8
            qx75rEPnO33bWJQCUCcBTAnWcLUDKPiTGP383F6V9OISTUDL27IQE6rZAcsyATgV
            hL7OQAvto2UrO9cxgQKwN0kGD74cJfGmyr6srbfUS98g0xJrcKfn0kvwD0KYGOEm
            GUaRK+TuzJ4lhd2V7Y5GMOBnWB2v4ZP3Fy9FmAyzo/zAA0itNVwewW3W70irterW
            F2sMHAD0Cogtwe1gCroDw4YqtgnwkX36xGK0e+kdI3iqe475rQWXlYfYSUQjixhZ
            iIjNCmVF7N7sDP0aSA6KGsXA5b05RNxE5a9zan41L/ULJT5cXNhSO5KX2DXBm1O5
            hdn9MxizaPGGcOtO73wwhwAQ0kAR2Yz6z3zHOjvJDaY4lqxzMcJ5JqCkKPJFOJM4
            V4x2VdlTAUp7uZI0l90tytKZ3dI2DpjLRbTheGbNT4bZa7yrMVmnk8FSMKUJp6PS
            ewXA1ZDpcM8xNUCxZs0m+NGZheJi6IU6URKg386sNGeyUQB0fZSnERGz/jG0kj/S
            XgG3yoEy2SNBBw+Zau8dmyQ2dh5zLRhdUNTcaqTQVlesvcQSfwYM4KxZzu+Qy8Mj
            0iaqa2JKmsKNejhO8ZyEGhmaEUI+ofT9soBL1VJBqHdFE+Lh2g6jd2yBpfa9RQc=
            =zRUt
            -----END PGP MESSAGE-----
          fp: 82B6F581AA9BAC43F18A9D2E8F13E77F0EF448C4
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
