---
all:
  vars:
    ssh_keys_access:
      - filecoin
      - glacierwalrus
      - ognots
      - magik6k
      - aayush
      - stebalien
      - jennifer
      - TippyFlitsUK
      - rjan90
      - Reiers
      - zenground0
      - circleci
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            ec2-54-221-161-132.compute-1.amazonaws.com:
        preminer1:
          hosts:
            ec2-34-207-107-191.compute-1.amazonaws.com:
        preminer2:
          hosts:
            ec2-34-228-241-196.compute-1.amazonaws.com:
        #preminer3:
        #  hosts:
        #    preminer-3.butterfly.fildev.network:
        #preminer4:
        #  hosts:
        #    preminer-4.butterfly.fildev.network:
        #preminer5:
        #  hosts:
        #    preminer-5.butterfly.fildev.network:
        bootstrap0:
          hosts:
            ec2-54-225-12-123.compute-1.amazonaws.com:
        bootstrap1:
          hosts:
            ec2-100-24-17-233.compute-1.amazonaws.com:
        toolshed0:
          hosts:
            ec2-34-201-220-22.compute-1.amazonaws.com:
        toolshed1:
          hosts:
            ec2-34-201-169-156.compute-1.amazonaws.com:
        scratch0:
          hosts:
            ec2-54-236-14-224.compute-1.amazonaws.com:
        #scratch1:
        #  hosts:
        #    scratch-1.butterfly.fildev.network:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    t01002:
      children:
        preminer2:

    #t01003:
    #  children:
    #    preminer3:

    #t01004:
    #  children:
    #    preminer4:

    #t01005:
    #  children:
    #    preminer5:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        faucet:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:
    #    t01003:
    #    t01004:
    #    t01005:

    toolbox:
      children:
        faucet:

    faucet:
      children:
        toolshed0:

    preminer:
      children:
        t01000:
        t01001:
        t01002:
    #    t01003:
    #    t01004:
    #    t01005:

    bootstrap:
      children:
        bootstrap0:
        bootstrap1:

    scratch:
      children:
        scratch0:
    #    scratch1:
