---
all:
  vars:
    ssh_keys_access:
      - filecoin
      - glacierwalrus
      - ognots
      - travisperson
      - kubuxu
      - magik6k
      - whyrusleeping
      - whysosirius
      - vyzo
      - aayush
      - mg
      - anorth
      - stebalien
      - jennifer
      - geoff-vball
      - TippyFlitsUK
      - rjan90
      - Reiers
      - LexLuthr
      - zenground0
      - circleci
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            preminer-0.butterfly.fildev.network:
        preminer1:
          hosts:
            preminer-1.butterfly.fildev.network:
        preminer2:
          hosts:
            preminer-2.butterfly.fildev.network:
        preminer3:
          hosts:
            preminer-3.butterfly.fildev.network:
        preminer4:
          hosts:
            preminer-4.butterfly.fildev.network:
        preminer5:
          hosts:
            preminer-5.butterfly.fildev.network:
        bootstrap0:
          hosts:
            bootstrap-0.butterfly.fildev.network:
        bootstrap1:
          hosts:
            bootstrap-1.butterfly.fildev.network:
        toolshed0:
          hosts:
            toolshed-0.butterfly.fildev.network:
        toolshed1:
          hosts:
            toolshed-1.butterfly.fildev.network:
        scratch0:
          hosts:
            scratch-0.butterfly.fildev.network:
        scratch1:
          hosts:
            scratch-1.butterfly.fildev.network:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    t01002:
      children:
        preminer2:

    t01003:
      children:
        preminer3:

    t01004:
      children:
        preminer4:

    t01005:
      children:
        preminer5:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        faucet:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:
        t01003:
        t01004:
        t01005:

    toolbox:
      children:
        faucet:
        stats:

    faucet:
      children:
        toolshed0:

    stats:
      children:
        toolshed0:

    preminer:
      children:
        t01000:
        t01001:
        t01002:
        t01003:
        t01004:
        t01005:

    bootstrap:
      children:
        bootstrap0:
        bootstrap1:

    scratch:
      children:
        scratch0:
        scratch1:
