---
all:
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            preminer-0.butterfly.fildev.network:
        preminer1:
          hosts:
            preminer-1.butterfly.fildev.network:
        bootstrap0:
          hosts:
            bootstrap-0.butterfly.fildev.network:
        bootstrap1:
          hosts:
            bootstrap-1.butterfly.fildev.network:
        toolshed0:
          hosts:
            toolshed-0.butterfly.fildev.network:
        toolshed1:
          hosts:
            toolshed-1.butterfly.fildev.network:
        scratch0:
          hosts:
            scratch-0.butterfly.fildev.network:
        scratch1:
          hosts:
            scratch-1.butterfly.fildev.network:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        faucet:

    lotus_miner:
      children:
        t01000:
        t01001:

    toolbox:
      children:
        faucet:
        stats:
        chainwatch:

    faucet:
      children:
        toolshed0:

    stats:
      children:
        toolshed0:

    chainwatch:
      children:
        toolshed0:

    preminer:
      children:
        t01000:
        t01001:

    bootstrap:
      children:
        bootstrap0:
        bootstrap1:

    scratch:
      children:
        scratch0:
        scratch1:

    sentinel:
      children:
        toolshed1:
