---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-daemon
  labels:
    app: lotus-fullnode-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.ports.api }}"
    prometheus.io/path: /debug/metrics
spec:
  type: ClusterIP
  selector:
    app: lotus-fullnode-app
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ports.api }}
      targetPort: 1234
      name: api
    - protocol: TCP
      port: {{ .Values.ports.libp2p }}
      targetPort: 1347
      name: libp2p
