promtail_version: "3.3.2"
promtail_binary_url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
promtail_install_path: "/usr/local/bin/promtail"
promtail_config_path: "/etc/promtail"
promtail_user: "promtail"
promtail_group: "promtail"
loki_server: "http://localhost:3100"
loki_username: ""
loki_password: ""