apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/storage/
- ../../../base/images/
- ../mainnet/cluster
- ../calibrationnet/cluster
- ../butterflynet/cluster

