apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lotus-stats
spec:
  install:
    timeout: 300m
    remediation:
      retries: 100
  upgrade:
    timeout: 300m
    remediation:
      retries: 100
  chart:
    spec:
      chart: lotus-stats
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: filecoin-project-charts
      version: 0.1.2
  interval: 1m0s
  # The values are merged in the order given, with the later values overwriting earlier. These values always have a lower priority 
  valuesFrom:
  - kind: ConfigMap
    name: lotus-stats-common-values
  - kind: ConfigMap
    name: lotus-stats-network-values
  - kind: ConfigMap
    name: lotus-stats-values
