image:
  tag: v1.18.0

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 160Gi

importSnapshot:
  enabled: true
  strategy: url
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json
  - name: GODEBUG
    value: madvdontneed=1
  - name: DISABLE_PRE_MIGRATIONS
    value: "1"
  # - name: LOTUS_JAEGER_AGENT_HOST
  #   valueFrom:
  #     fieldRef:
  #       apiVersion: v1
  #       fieldPath: status.hostIP
  # - name: LOTUS_JAEGER_AGENT_PORT
  #   value: "6831"

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  network: mainnet

persistence:
  datastore:
    enabled: true
    size: "16000Gi"
