apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: butterflynet
  namespace: ntwk-butterflynet
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: github-auth
  url: https://github.com/filecoin-project/lotus-infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: butterflynet
  namespace: ntwk-butterflynet
spec:
  decryption:
    provider: sops
    secretRef:
      name: cluster-sops-gpg
  interval: 5m0s
  path: ./kubernetes/gitops/prod/us-east-1/butterflynet/tenant
  prune: true
  # serviceAccountName: butterflynet
  sourceRef:
    kind: GitRepository
    name: butterflynet
  validation: client
