---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: butterflynet-lotus
  namespace: ntwk-butterflynet
spec:
  interval: 5m
  image: docker.io/travisperson/lotus
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: butterflynet-lotus
  namespace: ntwk-butterflynet
spec:
  filterTags:
   pattern: 'butterflynet-.*'
  policy:
    semver:
      range: butterflynet-v0.x.x
  imageRepositoryRef:
    name: butterflynet-lotus

