image:
  pullPolicy: Always
  tag: "1.1.1"

indexResolver:
  replicas: 1
  s3Resolver:
    bucket: "filecoin-snapshots-mainnet-staging"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access

  loadBalancer:
    enabled: false

snapshots:
  uploads:
    enabled: true
    bucket: "filecoin-snapshots-mainnet-staging"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access
  additionalEnv:
  - name: "FCA_CREATE_RETRIEVAL_ENDPOINT_PREFIX"
    value: "https://pub-72366a891cfb4f1d8d3d518390c52e6e.r2.dev"
