apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: fullnode
spec:
  install:
    timeout: 5m
    remediation:
      retries: 100
  upgrade:
    timeout: 5m
    remediation:
      retries: 100
  chart:
    spec:
      chart: lotus-fullnode
      sourceRef:
        apiVersion: source.toolkit.fluxcd.io/v1beta1
        kind: HelmRepository
        name: filecoin-project-charts
      version: 0.4.3
  interval: 1m0s
  # The values are merged in the order given, with the later values overwriting earlier. These values always have a lower priority
  valuesFrom:
  - kind: ConfigMap
    name: fullnode-common-values
  - kind: ConfigMap
    name: fullnode-network-common
  - kind: ConfigMap
    name: fullnode-values
