#!/usr/bin/env bash

if [ -z "$CIRCLECI_TOKEN" ]; then
  echo you must set a circleci token to CIRCLECI_TOKEN
fi

curl --request POST \
  --url https://circleci.com/api/v2/project/gh/filecoin-project/lotus-infra/pipeline \
  --header "Circle-Token: $CIRCLECI_TOKEN" \
  --header 'content-type: application/json' \
  --data '{
    "branch": "master",
    "parameters":{
      "api_workflow_requested": "lotus-devnet-ansible",
      "lotus_deploy_network": "butterfly.fildev.network",
      "lotus_install_network": "butterflynet",
      "override_tag": "v1.8.0"
    }}'

