#!/usr/bin/env bash

if [ -z "$CIRCLECI_TOKEN" ]; then
  echo you must set a circleci token to CIRCLECI_TOKEN
fi

curl --request POST \
  --url https://circleci.com/api/v2/project/gh/filecoin-project/lotus-infra/pipeline \
  --header "Circle-Token: $CIRCLECI_TOKEN" \
  --header 'content-type: application/json' \
  --data '{
    "branch": "master",
    "parameters":{
      "api_workflow_requested": "helm-deploy",
      "namespace": "ntwk-butterfly-fullnode",
      "release": "fullnode-0",
      "chart": "filecoin/lotus-fullnode",
      "chart_version": "0.3.1",
      "override_tag": "v1.5.0"
    }}'

