apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 1h
  releaseName: goldilocks
  chart:
    spec:
      chart: goldilocks
      version: "6.5.x"
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable
        namespace: "[[ KUSTOMIZE ME! ]]"
  values:
    resources:
      limits:
        cpu: 50m
        memory: 512Mi
      requests:
        cpu: 50m
        memory: 512Mi
