---
- name: ensure authorized keys
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - public-keys/kubuxu
    - public-keys/lanzafame
    - public-keys/magik6k
    - public-keys/ognots
    - public-keys/travisperson
    - public-keys/whyrusleeping
