lotus_miner_presealed: "yes"
lotus_miner_systemd_extras:
  LimitNOFILE: 32768
  LimitNOFILESoft: 24576

lotus_miner_verified_deals: false
lotus_miner_data_root: "/vagrant"
lotus_miner_presealed_sectors:
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/000"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/032"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/064"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/096"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/128"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/160"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/192"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/224"
