kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io2-low-throughput
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  type: io2
  iopsPerGB: "20"
  allowAutoIOPSPerGBIncrease: "true"
