name: "Lotus Ansible Prepare"
description: "Composite action to prepare using Lotus and Ansible"
inputs:
  branch:
    description: "Lotus Branch or Tag"
    required: true
  PRIVATE_SSH_KEY:
    description: "Private SSH Key used to connect to the network"
    required: true
  AWS_ACCESS_KEY_ID:
    description: "AWS Access Key ID"
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: "AWS Secret Access Key"
    required: true
  AWS_REGION:
    description: "AWS Region"
    required: true
  ANSIBLE_VAULT_PASSWORD:
    description: "Ansible Vault Password"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Env
      shell: bash
      run: |
        echo "GOPATH=${GITHUB_WORKSPACE}/.go_workspace" >> $GITHUB_ENV
        echo "LOTUSROOT=${GITHUB_WORKSPACE}/.go_workspace/src/github.com/filecoin-project/lotus" >> $GITHUB_ENV

    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
      with:
        ssh-private-key: ${{ inputs.PRIVATE_SSH_KEY }}

    - name: Setup ssh-agent
      uses: webfactory/ssh-agent@dc588b651fe13675774614f8e6a936a468676387 # v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY_F3 }}

    - name: Configure SSH - use Ubuntu user and do not check host key
      shell: bash
      run: |
        echo -e "Host *\n  User ubuntu\n  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - uses: actions-rust-lang/setup-rust-toolchain@v1

    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - uses: actions/setup-go@v5
      with:
        go-version: "1.21.7"

    - name: Install Ansible Playbook
      shell: bash
      run: |
        pip install ansible

    - name: Clone Lotus Repository
      uses: actions/checkout@v4
      with:
        repository: filecoin-project/lotus
        ref: ${{ inputs.branch }}
        path: ${{ env.LOTUSROOT }}

    - name: Setup Secrets
      shell: bash
      working-directory: ansible
      env:
        ANSIBLE_VAULT_PASSWORD: ${{ inputs.ANSIBLE_VAULT_PASSWORD }}
      run: |
        echo ${ANSIBLE_VAULT_PASSWORD} > .vault_password
