kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: io2
  # annotations:
  #   storageclass.kubernetes.io/is-default-class: "true"
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: io2
