image:
  pullPolicy: Always
  tag: "1.3.0"

indexResolver:
  replicas: 3
  s3Resolver:
    bucket: "filecoin-snapshots-calibnet-production"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access

  loadBalancer:
    enabled: true
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:759815798766:certificate/f3079147-69f3-4229-a726-f50970ba7244
      service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
      external-dns.alpha.kubernetes.io/hostname: snapshots.calibrationnet.filops.net
      external-dns.alpha.kubernetes.io/alias: "true"
      external-dns.alpha.kubernetes.io/ttl: "60"

snapshots:
  uploads:
    enabled: true
    bucket: "filecoin-snapshots-calibnet-production"
    endpoint: "https://eafecb340a3ce23027e1eba779ed4d91.r2.cloudflarestorage.com"
    secretName: r2-access
  additionalEnv:
  - name: "FCA_CREATE_RETRIEVAL_ENDPOINT_PREFIX"
    value: "https://pub-f851d666b9a54f60bd93202926618941.r2.dev"
  - name: "FCA_CREATE_PROGRESS_UPDATE"
    value: "60s"
  - name: "FCA_CREATE_NAME_PREFIX"
    value: "minimal/"
  - name: "GOLOG_LOG_FMT"
    value: "json"
  nodes:
  - /dns/lws-node-0-fullnode-lotus-daemon/tcp/1234
  - /dns/lws-node-1-fullnode-lotus-daemon/tcp/1234
# Exclude 2 as we're testing a genesis sync on it and it man not be not safe for snapshots
#  - /dns/lws-node-2-fullnode-lotus-daemon/tcp/1234
  - /dns/lws-node-3-fullnode-lotus-daemon/tcp/1234
