apiVersion: v1
stringData:
    ACCESS_KEY: ENC[AES256_GCM,data:hrtx31ibVLmbJEUWsTqUNafNYY+pFyXwO2Vjt427U6Q=,iv:BDvIHEB+vyL3p4cw5I3WuW2ww3Q/HAsgsthSujF8lJs=,tag:knQ1cr2NrOHC82FqORp6qQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:gI3iyjomvPKagMHDw292/njw5DlS+YP2/6JlBFyqXgE7VYFvj0hi30suO0ib8xTRsJQ/Z+6tF08t+Z5RBD24Xg==,iv:aF0IvHsLQx7jh+lCg8X1q55UsPXuzI/IdSneMHwAdb0=,tag:DuNvej9pql8p3csEzyNkvw==,type:str]
kind: Secret
metadata:
    name: r2-access
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-12T08:58:01Z"
    mac: ENC[AES256_GCM,data:TD9K1DyyN4EWcaIs0y2eX/FFu8ya3Uj7Rm3QUlF/x/PFserxYqED2FXSwZzGjL/JdrRUPayErxwZ/Zi008mm+DsrDUD57ujZfhXDX+zT+TkwsFdhg3MeKJGVyIGD18Y1VowNt1f331uJgPbmO+dQXcav2a9QtTmilQYGw6Dmqds=,iv:DcUZjP1s5HqVbF+9U35oOBdBlVGDYFP5825gORvDPdo=,tag:IXiSxAangH4yrgPojWnfYg==,type:str]
    pgp:
        - created_at: "2023-10-12T08:47:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA10BBd9Ja1tnARAAvda98IoIfh7EKB1DPYEm5K0+02Tl21lC+QxvKE3BE6CW
            xaEVmtl6qF1Yja1gCxgtLIO1MxHA1K29O9jRwNgOpUc7CrUgvZowBkrrA8MpM/7a
            bV2lpd2PE1hN8beF51fEbVqfi4RnAmB40wpIXurc2Mvboql1jN5zXAaZuhc3rXp2
            rS6RS0BEpxBNHYTFnhO7WqcNxA6P/mFUvtRDKY+ThFttvoaHY0jznzTMlrKuL2Wn
            Qde8hmd3b0MKSKB/z75XZK3S2GmKKsS6LmBlunjpCR2DspVXyNOkzRaMyjPgFPlC
            lUDjf+nxkw+RQZn1UpZOxLq0AIcBgJR69MFRmWgVt+xSrsfhNXhjmBBU7DGgpyfV
            kimhAooqLXstYG78YmJhm6ilDOyNXPNR27Z6aOn5PjNWAPz6o/uKK6sl5CF3xUBR
            NuuTNkwTjbhMs1Of96mn2JSJIMqgKDujIexS2F0QYA3ez5i6ANR6BBWHlRE7S5Mi
            ARzbfd1LcTtUUyzxnSQhdjU4tRRT0K9XubJ9e9UcCwhfhPAxZpyYv+L5PLTcadVU
            +WPr2VISGwXTU6Qslj6nHi5Z4dEoz8YCvkKGF4uO7aOqSTmoNokGzksWA2V3ZWWS
            k8hbRM18txBhPCUOonWQAD8k5H/wY2d0pOfS6mKSzuRgfSaA0PGuMDOA+UEXoDfS
            XgFeA3tQL7F3T+qSOj5h1b0Ynd1r0kWx2VKJnFrmiCHidhe8QVm9IwLGRBeBgsa+
            7bz5j2qjg2I3THRXOxVATM7Ia7UuOvGK3LefqdEs4gG37jkd6Yg64VcQyqOOXhk=
            =oTgD
            -----END PGP MESSAGE-----
          fp: 82B6F581AA9BAC43F18A9D2E8F13E77F0EF448C4
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
