image:
  tag: df66f48f6

prometheusOperatorServiceMonitor: true

resources:
  requests:
    memory: 96Gi
    cpu: 8
  limits:
    memory: 112Gi
    cpu: 12

importSnapshot:
  enabled: false
  claimName: chain-exports
  network: mainnet
  exportRelease: export-full-archive
  exitCodeOnMissing: 0

daemonEnvs:
  - name: GOLOG_LOG_FMT
    value: json

daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]

additionalLabels:
  network: mainnet

persistence:
  datastore:
    enabled: true
    storageClassName: "ebs-csi"
    size: "2000Gi"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - topologyKey: "kubernetes.io/hostname"
      labelSelector:
        matchExpressions:
        - key: app
          operator: In
          values:
          - lotus-fullnode-app
        - key: network
          operator: In
          values:
          - mainnet

