# mainnet

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-bootstrap-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-view
subjects:
  - kind: Group
    name: ntwk-mainnet-bootstrap-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-bootstrap-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-bootstrap-exec
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-edit
subjects:
  - kind: Group
    name: ntwk-mainnet-disputer-edit
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-view
subjects:
  - kind: Group
    name: ntwk-mainnet-disputer-exec
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-exec
subjects:
  - kind: Group
    name: ntwk-mainnet-disputer-exec
roleRef:
  kind: Role
  name: ntwk-mainnet-disputer-exec
  apiGroup: rbac.authorization.k8s.io
