# mainnet

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ntwk-mainnet-bootstrap
  name: ntwk-mainnet-bootstrap-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ntwk-mainnet-disputer
  name: ntwk-mainnet-disputer-exec
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
