apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrelease.yaml

configMapGenerator:
- files:
  - values.yaml=lighweight-snapshot-chain-archiver.yaml
  name: lighweight-snapshot-chain-archiver

configurations:
  - kustomizeconfig.yaml
