apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- helmrelease.yaml

configMapGenerator:
- files:
  - values.yaml=lightweight-snapshot-chain-archiver.yaml
  name: lightweight-snapshot-chain-archiver-common-values

configurations:
  - kustomizeconfig.yaml
