# Default values for go-filecoin-monitoring.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
domain: lotus-metrics.kittyhawk.wtf
domainInternal: lotus-metrics-internal.kittyhawk.wtf
metricsRange: 30m
metricsRefresh: 30s
grafana:
  image:
    repository: 657871693752.dkr.ecr.us-east-1.amazonaws.com/lotus-grafana
    tag: v1.5
  sidecar:
    datasources:
      enabled: true
  persistence:
    type: pvc
    enabled: true
    storageClassName: standard-resize
    accessModes: ["ReadWriteOnce"]
    size: 15Gi
  service:
    type: LoadBalancer
    port: 443
    portName: https
    targetPort: 8000
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:657871693752:certificate/468a4a8a-3778-44ad-821f-d788bb2e898d"
      external-dns.alpha.kubernetes.io/hostname: lotus-metrics.kittyhawk.wtf
      external-dns.alpha.kubernetes.io/alias: "true"
      external-dns.alpha.kubernetes.io/ttl: "60"
  tolerations:
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "monitoring"
      operator: "Equal"
      value: "true"
      effect: "NoExecute"
  nodeSelector:
    monitoring: "true"
  env:
    GF_AUTH_DISABLE_LOGIN_FORM: "false"
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
    GF_SMTP_ENABLED: "true"
    GF_SMTP_HOST: "smtp.mailgun.org:587"
    GF_SMTP_FROM_ADDRESS: "no-reply@mg.kittyhawk.wtf"
    GF_SMTP_FROM_NAME: "Lotus Grafana Admin"
  extraContainers:
    - name: nginx
      image: bitnami/nginx:1.16
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: config-volume
          mountPath: /opt/bitnami/nginx/conf/server_blocks
          readOnly: true
  extraConfigmapMounts:
    - name: config-volume
      mountPath: /opt/bitnami/nginx/conf/server_blocks
      configMap: lotus-grafana-nginx-sidecar
      readOnly: true
  smtp:
    existingSecret: mailgun
