apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/gateway

namePrefix: staging-ethrpc-chain-love-

configMapGenerator:
- files:
  - values.yaml=values.yaml
  name: gateway-values
