---
# Create a ClusterRole which provides access to managing secrets. This role should only provide
# enough access to allow for lotus-daemons to create their own secrets on startup
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-writer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
