module "toolshed" {
  source = "../lotus_node"
  name = "toolshed"
  instance_type = var.faucet_instance_type
  availability_zone = var.availability_zone
  ami = var.ami
  zone_id = aws_route53_zone.subdomain.id
  key_name = var.key_name
  environment = var.environment
  lotus_network = var.name
}
module "bootstrappers" {
  source = "../lotus_node"
  name = "bootstrapper"
  scale = var.bootstrapper_count
  instance_type = var.bootstrapper_instance_type
  availability_zone = var.availability_zone
  ami = var.ami
  zone_id = aws_route53_zone.subdomain.id
  key_name = var.key_name
  environment = var.environment
  lotus_network = var.name
}
module "miners" {
  source = "../lotus_node"
  name = "miner"
  scale = var.miner_count
  volumes = var.miner_volumes
  instance_type = var.miner_instance_type
  availability_zone = var.availability_zone
  ami = var.ami
  zone_id = aws_route53_zone.subdomain.id
  key_name = var.key_name
  environment = var.environment
  lotus_network = var.name
}
module "scratch" {
  source = "../lotus_node"
  name = "scratch"
  scale = var.scratch_count
  volumes = var.scratch_volumes
  instance_type = var.miner_instance_type
  availability_zone = var.availability_zone
  ami = var.ami
  zone_id = aws_route53_zone.subdomain.id
  key_name = var.key_name
  environment = var.environment
  lotus_network = var.name
}
