apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gateway
spec:
  chart:
    spec:
      version: 0.1.3-rc1
  # XXX: Temporary to try to fix stuck reconciliation
  interval: 10m
