- include_tasks: ../../../includes/required_vars.yml
- include_tasks: ../../../includes/lotus_general_runtime_deps.yml

- name: Reset system
  block:
    - name: Ensure miner stopped
      service:
        name: lotus-miner
        state: stopped
      ignore_errors: yes
    - name: Remove miner repository
      file:
        path: "{{ lotus_miner_path }}"
        state: absent
    - name: Remove presealed metadata
      file:
        path: "{{ lotus_miner_presealed_metadata }}"
        state: absent
    - name: Truncate log file
      shell:
        cmd: truncate -s 0 "{{ lotus_miner_golog_file }}"
  when: lotus_miner_reset == "yes"

- name: Copy binary
  copy:
    src: "{{ lotus_miner_binary_src }}"
    dest: /usr/local/bin/lotus-miner
    owner: root
    group: root
    mode: "0755"
  when: lotus_miner_binary_src is defined

- name: Copy lotus-seed binary
  copy:
    src: "{{ lotus_seed_binary_src }}"
    dest: /usr/local/bin/lotus-seed
    owner: root
    group: root
    mode: "0755"
  when: lotus_seed_binary_src is defined

- name: Ensure miner repository exists
  file:
    path: "{{ lotus_miner_path }}"
    state: directory
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0750"

- name: Ensure LOTUS_MINER_PATH global env is set
  lineinfile:
    path: /etc/environment
    regex: "^LOTUS_MINER_PATH"
    line: LOTUS_MINER_PATH="{{ lotus_miner_path }}"

- name: Ensure log file exists
  file:
    state: touch
    path: "{{ lotus_miner_golog_file }}"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0644"

- name: Ensure service file
  template:
    src: ../templates/lotus-miner.service.j2
    dest: /etc/systemd/system/lotus-miner.service
    owner: root
    group: root
    mode: "0644"
  notify:
    - systemd-daemon-reload

- name: Ensure lotus configuration
  template:
    src: ../templates/config.toml.j2
    dest: "{{ lotus_miner_path }}/config.toml"
    owner: "{{ lotus_user }}"
    group: "{{ lotus_user }}"
    mode: "0644"

- name: Ensure pre-script (presealed)
  template:
    src: ../templates/lotus-miner-init-presealed.j2
    dest: /usr/local/bin/lotus-miner-init
    owner: root
    group: root
    mode: "0755"
  when: lotus_miner_presealed == "yes"

- name: Ensure pre-script (not presealed)
  template:
    src: ../templates/lotus-miner-init.j2
    dest: /usr/local/bin/lotus-miner-init
    owner: root
    group: root
    mode: "0755"
  when: lotus_miner_presealed == "no"

- name: Ensure parameters are downloaded
  become_user: "{{ lotus_user }}"
  shell: /usr/local/bin/lotus-miner fetch-params "{{ lotus_miner_sector_size }}"
  when: lotus_miner_ensure_params | bool

- name:
  include_tasks: import_wallet.yml
  when: lotus_miner_import_wallet | bool

- name: Ensure lotus miner service enabled
  systemd:
    name: "lotus-miner"
    enabled: yes

- name: Ensure ufw application rules
  template:
    src: ../templates/ufw.profile.j2
    dest: /etc/ufw/applications.d/lotus-miner
    owner: root
    group: root
    mode: 0644

- name: Ensure ufw allow
  ufw:
    rule: allow
    name: "Lotus Miner"
