secrets:
  jwt:
    enabled: true
    secretName: lightweight-snapshot-node-jwt-secret

image:
  tag: v1.22.1-calibnet

importSnapshot:
  # Using the snapshot provided by TippyFlits
  # see https://filecoinproject.slack.com/archives/C0328U5N4HL/p1682357430913569?thread_ts=1682271745.395409&cid=C0328U5N4HL
  enabled: true
  url: https://pub-f851d666b9a54f60bd93202926618941.r2.dev/filecoin-snapshots-calibnet-production/manual/499775_2023_04_24T15_00_00_UTC8.car
  strategy: "url"
