---

- name: postgresql.conf
  lineinfile:
    path: "/etc/postgresql/{{ pgdg_version }}/main/postgresql.conf"
    regexp: '#?{{ item.k }} =.*'
    line: '{{ item.k }} = {{ item.v }}'
    state: "{{ item.state | default('present') }}"
  with_items: "{{ tdb_postgresql_conf }}"
  register: tdb_conf

- name: (re)start postgresql
  systemd:
    name: "postgresql@{{ pgdg_version }}-main.service"
    state: "{% if tdb_conf is changed %}restarted{% else %}started{% endif %}"

- name: create extension
  become: true
  become_user: postgres
  postgresql_ext:
    name: timescaledb
    db: "{{ item.database }}"
  with_items: "{{ pgdg_users }}"
