apiVersion: v1
data:
    auth-jwt-private: ENC[AES256_GCM,data:+zliXFSLfGfykcGpNrqNSdyZCoqvfoAQowOEvgbW4iLb5RNm84T97h72upSL4NtN7zS/kTRCa1QoYqSh1ErcpBgf4PHzXKnW5ifa4YECtcEaNCr4Gz91+ZMM3umpL4ecUNLxAoY5eCIR8FVRcqHXod6HSJ8=,iv:OyF+jDru6rQ2b8+6QL9WCqKvdlffdI4OPvFj7Xc/hKQ=,tag:lodHyTTSJs8RLntlZJOEUw==,type:str]
    jwt-all-privs-token: ENC[AES256_GCM,data:Qml20+W4aefIdzzmcIMNTlRA7ni0lcYOWNriK9LN3/InOoDSjmQ8VAhediE/kPfXOayzv2jHje4FZrsapkIVSmOZVBisg+tXNXxn/S4zMW70aDXUAkseFIugtguxl01dkQd5ElVfbKYwDhLcUvX+xPMVd3TVLSQE/fnUyMQ7RkkL4SGFCUCfWFSc20pfel47+q9pScZvJhtADnNhFLpGfEgZk3HxPrbRjVTJLZiQvF1EMigOoSiewQ==,iv:Z+wS03PlJ9zbH/e8dWymc7yu46vAZARUWd+fNBVLsvg=,tag:DD2z9kfepo/R+YFNE1cUZA==,type:str]
    jwt-ro-privs-token: ENC[AES256_GCM,data:lr7GLSpkKIKtH7F9pFGHjWjD0IHqbCuJ9Ht10SGOMqPtwMgbLhe0K1CpYk8O6Y3R9utVwOXOt1fwn22VoglEzUt0gah5B2lnj11Mdl15Sa+oaXn7OzOuuUfGsWTyrHOlcA8XKgi+uPn7ajDoSa/MPM4Bu32DoHwSyDKGkGlEIfHFwVQmV4Y61OdAuRc=,iv:87R1rVaf2odh+Kuk/yP/jnWakpszW/Ye02gHf+vksbw=,tag:8cvph7crPrCalIme2TXf7g==,type:str]
    jwt-rw-privs-token: ENC[AES256_GCM,data:s7+IhARhDVYFT7AJf7lpdFono3j3dBS9G/nRoszuHuAw3jxiUw2QH7Vwk4p0FrjtnxvukEd/OPoWa5/vBvxA6+/uqX5Tx/wpdFguIazxE0Wk9CgiyNRxA7Ul6xjyoFQaFXp41w7JMafQ4xAmPIr2zfSZUxBCzyNAZZDL5S71hFPO5dZH3dkMOdW4T2/6JllGelkMO5ASvtrBpZW4,iv:jYO87daTWwi5zkPpPU4koBPSgWLMmb1yijmHItqbMfA=,tag:++7ihzzvmrlWzV+AMCeI3A==,type:str]
    jwt-so-privs-token: ENC[AES256_GCM,data:M5XR/insn1ZiSoxDRfvXx1saLNNjeo4SlqHvU+2+9TRSUGI2tWITQtN9SM5gJGLJMt/fmdsy1T0hEVrK+/YriPvAXiaMEcP9AM8U4b90eCNt00FWn/4ddJtZpntkDiN/HpSbHwTfpG+4iurxXw37CAcvdIUS2XZAISvqntwicia/yuabYma/nNd3mLc=,iv:Fz48suoqagMMWyKpJPQAdTqFI+28gRBQmvBM/RGnrhA=,tag:hP3g23hjMa3XcetWK7nW/A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: lightweight-snapshot-node-jwt-secret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-12-15T16:43:47Z"
    mac: ENC[AES256_GCM,data:6pQCyC5dG2XCO2N7VMGJE/THn565U9yXn79sFz203g3Z3JCFawxuGsjATLwUUdssJyh8/E9LpNlwWhds1xZaNaF/4COeWzMRgDBm8XfVzDr6+nG1UukKg3+kPossL0izosWKrHwkdv9zxife10SN445oD6OJtgYojKGkSOeVvgo=,iv:5Wglpwwtw88EFL0v1ma0EMZkpCODzhKfej0n5k4BdVE=,tag:UQhcvDPSJujOyciiTVRCeQ==,type:str]
    pgp:
        - created_at: "2022-12-15T16:43:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAzhHTTGTeReUAQ/+KxkC+JerpJ7HpDXvkny/TENUHmBxp75ol/xBSIIQjurL
            4FGcOakK+VZXVrDYQNpNZqf33fkI/Xj62o3tMLZ6wIw/uYByZrabvlRSDyLr4SXL
            UK67NDQa7Sn4Cjiq1ZPjsrDRkKJ1uFGj8gL4KJxSpcQeeMGqCczGh0mJR4zmSVMn
            9/vBict0wJTyISfUBUj6DJJSzj2Sj7tquLpxo81N6Syn29TbNWe9YaiFbxELSClt
            KaPp01AxdFHHqC0A9zqFOAfeWG/m6nQNZRqf7vzIgx/kCVHAfd+D5akG7LF+BxfQ
            kWz3gfpKExwd3WnnMxaJz9MbtzR6AIyIBPJv97tzS/q2tK1nNpn8yXwDM6HBhjog
            d5D3hk1Bjs9GtQKHnDC8It/NbclxO0xIZDYtvVe3GHXeIQU+smLDWnwmPMtbAqEJ
            evPwGCEtKYfmhjzl6idSU25RUaLlvf6jN4yHc/UuzCAwNyUEqQrLQ3C0A1hV11ar
            jOSTIMPuLgB5os5RSEm9fOrha6Fa/MP0m2BfD6Ft7m1jPdVEOKYrJul9KNmeQyrW
            6y5BeGzeoLFCSyOz4sFtBvELYZIWqfTidin2LQ1wnvaETk38DKsKCgYiQgs/hhDA
            Cga+/4+UncpmHtjUqHRVktViChodqGNcARUpDEn1wyn9g86/YU+0NNxCiUOsJ4vS
            XgGz6kl3XmTdTCKlRez4zdIyRysUzoHtwuaKsM8F+krqG86t2jt6BmkCRG1s/GR7
            JYj9zPZwka/i99ilVEDERJgL3e04WJwr/jzzEJBcOXmSq2u5BGUrH4zICQwGCUw=
            =66lV
            -----END PGP MESSAGE-----
          fp: A50558D3030D9A1513E0C44C473253F56BEC6FF5
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
