image:
  repository: filecoin/lotus-all-in-one
  tag: v1.20.3-rpc-p01-hf02
  pullPolicy: Always

# volumeClaims:
volumeClaimTemplates:
- metadata:
    name: lotus-sqlite
  spec:
    storageClassName: gp3-retain
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
application:
  name: lotus-gateway-ethrpc
  labels: []
  replicas: 2
  container:
    name: lotus-gateway
    command:
    - /usr/local/bin/lotus-gateway
    args:
    - run
    - --api-max-lookback
    - "24h0m0s"
    - --rate-limit
    - "3000"
    - --per-conn-rate-limit
    - "100"
    - --rate-limit-timeout
    - 10s
    # - --conn-per-minute
    # - "6"
    env: []
    ports:
    - containerPort: 2346
      name: lotus-gw
    livenessProbe:
      httpGet:
        port: 2346
        path: /health/livez
      initialDelaySeconds: 60
      periodSeconds: 60
    readinessProbe:
      httpGet:
        port: 2346
        path: /health/readyz
      initialDelaySeconds: 60
      periodSeconds: 60
  secrets: []
  configMaps: []
  services:
  - type: LoadBalancer
    externalTrafficPolicy: Local
    selector:
      app: lotus-gateway-ethrpc
    ports:
    - protocol: TCP
      port: 80
      targetPort: 2346
      name: lotus-gw
  ingresses:
  - annotations:
      nginx.ingress.kubernetes.io/configuration-snippet: |
        more_set_headers "Access-Control-Allow-Origin: *";
        more_set_headers "Access-Control-Allow-Headers: content-type";
        more_set_headers "Access-Control-Allow-Methods: POST, OPTIONS";
        more_set_headers "Access-Control-Max-Age: 300";
        if ($request_method = OPTIONS) {
          more_set_headers "Content-Length: 0";
          return 204;
        }
    spec:
      ingressClassName: nginx
      rules:
      - host: eth.api.chain.love
        http:
          paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: eth-clove-gateway-lotus-gateway-ethrpc-0
                port:
                  name: lotus-gw
  storage: []

lotus:
  enabled: true
  image: docker.io/filecoin/lotus-all-in-one:v1.20.3-rpc-p01-hf02
  extraEnv:
    LOTUS_API_LISTENADDRESS: /ip4/0.0.0.0/tcp/1234/http
    LOTUS_FEVM_ENABLEETHRPC: "true"
  reset:
    enabled: true
    percent: 90
  extraVolumeMounts:
  - name: lotus-sqlite
    mountPath: /var/lib/lotus/sqlite

prometheus:
  serviceMonitor: true
  path: /debug/metrics
  port: lotus-gw
