---
all:
  children:
    vagrant:
      vars:
        ansible_user: vagrant 
      children:
        preminer0:
          hosts:
            10.10.100.100:
        bootstrap0:
          hosts:
            10.10.100.101:
        toolshed0:
          hosts:
            10.10.100.102:
        scratch0:
          hosts:
            10.10.100.103:

    t01000:
      children:
        preminer0:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        toolbox:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:

    toolbox:
      children:
        faucet:

    faucet:
      children:
        toolshed0:

    preminer:
      children:
        t01000:

    bootstrap:
      children:
        bootstrap0:

    scratch:
      children:
        scratch0:
