apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.claimName }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs
  volumeName: efs-{{ .Release.Namespace }}
  resources:
    requests:
      storage: 4096Gi
