image:
  repository: filecoin/lotus-all-in-one
  tag: v1.22.1 # {"$imagepolicy": "ntwk-mainnet:lotus-latest-release:tag"}
  pullPolicy: Always
application:
  name: lotus-gateway
  labels: []
  replicas: 2
  container:
    name: lotus-gateway
    command:
      - /usr/local/bin/lotus-gateway
    args:
      - run
      - --api-max-lookback
      - "24h0m0s"
      - --rate-limit
      - "3000"
      - --per-conn-rate-limit
      - "100"
      - --rate-limit-timeout
      - 10s
      # - --conn-per-minute
      # - "6"
    env: []
    ports:
      - containerPort: 2346
        name: lotus-gw
    livenessProbe:
      httpGet:
        port: 2346
        path: /health/livez
      initialDelaySeconds: 60
      periodSeconds: 60
    readinessProbe:
      httpGet:
        port: 2346
        path: /health/readyz
      initialDelaySeconds: 60
      periodSeconds: 60
  secrets: []
  configMaps: []
  services:
    - type: LoadBalancer
      externalTrafficPolicy: Local
      selector:
        app: lotus-gateway
      ports:
        - protocol: TCP
          port: 80
          targetPort: 2346
          name: lotus-gw
  ingresses:
    - annotations:
        nginx.ingress.kubernetes.io/configuration-snippet: |
          more_set_headers "Access-Control-Allow-Origin: *";
          more_set_headers "Access-Control-Allow-Headers: content-type";
          more_set_headers "Access-Control-Allow-Methods: POST, OPTIONS";
          more_set_headers "Access-Control-Max-Age: 300";
          if ($request_method = OPTIONS) {
            more_set_headers "Content-Length: 0";
            return 204;
          }
      spec:
        ingressClassName: nginx
        rules:
          - host: api-staging.chain.love
            http:
              paths:
                - pathType: Prefix
                  path: "/"
                  backend:
                    service:
                      name: staging-api-chain-love-gateway-lotus-gateway-0
                      port:
                        name: lotus-gw
  storage: []
lotus:
  enabled: true
  image: docker.io/filecoin/lotus-all-in-one:v1.22.1 # {"$imagepolicy": "ntwk-mainnet:lotus-latest-release"}
  reset:
    enabled: true
    percent: 90
  extraEnv:
    LOTUS_API_LISTENADDRESS: /ip4/0.0.0.0/tcp/1234/http
    LOTUS_FEVM_ENABLEETHRPC: "true"
    LOTUS_CHAINSTORE_ENABLESPLITSTORE: "true"
    LOTUS_CHAINSTORE_SPLITSTORE_COLDSTORETYPE: "discard"
    ## We need 4 finalities: 1 finality = 900 epochs, 1 epoch = 30s
    ## Finalities required for 24h of data: 24h / (900epochs * 30s / 3600s) = 3.2
    LOTUS_CHAINSTORE_SPLITSTORE_HOTSTOREMESSAGERETENTION: "4"

prometheus:
  serviceMonitor: true
  path: /debug/metrics
  port: lotus-gw
# nodeSelector:
#   "node.kubernetes.io/instance-type": "r5.2xlarge"
