---
all:
  children:
    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            preminer-0.nerpa.fildev.network:
        preminer1:
          hosts:
            preminer-1.nerpa.fildev.network:
        preminer2:
          hosts:
            preminer-2.nerpa.fildev.network:
        bootstrap0:
          hosts:
            bootstrap-0.nerpa.fildev.network:
        bootstrap1:
          hosts:
            bootstrap-1.nerpa.fildev.network:
        bootstrap2:
          hosts:
            bootstrap-2.nerpa.fildev.network:
        bootstrap3:
          hosts:
            bootstrap-3.nerpa.fildev.network:
        toolshed0:
          hosts:
            toolshed-0.nerpa.fildev.network:
        scratch0:
          hosts:
            scratch-0.nerpa.fildev.network:
        scratch1:
          hosts:
            scratch-1.nerpa.fildev.network:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    t01002:
      children:
        preminer2:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        faucet:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:

    toolbox:
      children:
        faucet:
        stats:
        chainwatch:

    faucet:
      children:
        toolshed0:

    stats:
      children:
        toolshed0:

    chainwatch:
      children:
        toolshed0:

    preminer:
      children:
        t01000:
        t01001:
        t01002:

    bootstrap:
      children:
        bootstrap0:
        bootstrap1:
        bootstrap2:
        bootstrap3:

    scratch:
      children:
        scratch0:
        scratch1:
