---
podManagementPolicy: Parallel

image:
  repository: filecoin/lotus-all-in-one
  pullPolicy: Always

application:
  name: lotus-gateway
  labels: []
  replicas: 3
  container:
    name: lotus-gateway
    command:
      - /usr/local/bin/lotus-gateway
    args:
      - run
      - --api-max-lookback
      - "3h0m0s"
      - --rate-limit
      - "3000"
      - --per-conn-rate-limit
      - "100"
      - --rate-limit-timeout
      - 10s
      # - --conn-per-minute
      # - "6"
    env: []
    ports:
      - containerPort: 2346
        name: lotus-gw
    livenessProbe:
      httpGet:
        port: 2346
        path: /health/livez
      initialDelaySeconds: 60
      periodSeconds: 60
    readinessProbe:
      httpGet:
        port: 2346
        path: /health/readyz
      initialDelaySeconds: 60
      periodSeconds: 60
  secrets: []
  configMaps: []
  services:
    - type: LoadBalancer
      externalTrafficPolicy: Local
      selector:
        app: lotus-gateway
      ports:
        - protocol: TCP
          port: 80
          targetPort: 2346
          name: lotus-gw
  storage: []

lotus:
  enabled: true
  reset:
    enabled: true
    percent: 90
  extraVolumeMounts:
  - name: lotus-sqlite
    mountPath: /var/lib/lotus/sqlite
  config:
    create: true
    content: |-
      [API]
        # We need to listen on 0.0.0.0 rather than 127.0.0.1 to
        # because the same web server server both API and metric requests
        # and prometheus is an external scraper
        ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
      [Chainstore]
        # Required due to bug in lotus
        # see https://github.com/filecoin-project/lotus/issues/11198
        EnableSplitstore = true
        [Chainstore.Splitstore]
          ColdStoreType = "discard"
      [Fevm]
        EnableEthRPC = true

prometheus:
  serviceMonitor: true
  path: /debug/metrics
  port: lotus-gw

# volumeClaims:
volumeClaimTemplates:
- metadata:
    name: lotus-sqlite
  spec:
    storageClassName: gp3-retain
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 25G
