version: '3'

services:
  influxdb:
    image: influxdb:latest
    container_name: vagrant-influxdb
    environment:
      - INFLUXDB_DB=lotus
    ports:
      - "18086:8086"

  grafana:
    image: grafana/grafana:latest
    container_name: vagrant-grafana
    ports:
      - "13000:3000"
    links:
      - influxdb

  postgres:
    image: postgres:11
    container_name: vagrant-postgres
    environment:
      POSTGRES_PASSWORD: protocol
    ports:
      - "15432:5432"
