---
- hosts: genesis
  vars:
    lotus_binary_src: /tmp/lotus
    lotus_miner_presealed_sector_src: /tmp/lotus-genesis-sectors
    lotus_miner_binary_src: /tmp/lotus-storage-miner
    lotus_miner_is_genesis: yes
    lotus_fountain_binary_src: /tmp/lotus-fountain
    lotus_fountain_wallet: "{{ lotus_wallet_address }}"
    ufw_profiles:
      - "{{ lotus_fullnode_ufw_profile }}"
      - "{{ lotus_fountain_ufw_profile }}"
    logz_inputs:
      - type: log
        paths:
          - "{{ lotus_golog_file }}"
        fields:
          logzio_codec: json
          token: "{{ logz_io_shared_token }}"
          type: lotus-daemon
        fields_under_root: true
        json.keys_under_root: false
        json.message_key: msg
        encoding: utf-8
        ignore_older: 3h
  roles:
    - role: telegraf
    - role: filebeat_logz_io
    - role: lotus_fullnode
    - role: lotus_miner
    - role: lotus_fountain
    - role: ufw
