---
- hosts: all
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - include_role: name=common
    - include_role: name=ntp
    - include_role: name=filebeat_logz_io
    - include_role: name=telegraf
    - include_role: name=ufw

- hosts: preminer
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - include_role: name=lotus_fullnode
      vars:
        lotus_import_peerkey: true
    - include_role: name=lotus_miner
      vars:
        lotus_miner_import_wallet: true

- hosts: bootstrap
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - include_role: name=lotus_fullnode
      vars:
        lotus_import_peerkey: true

- hosts: toolbox
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - include_role: name=lotus_fullnode
      vars:
        lotus_import_peerkey: true
    - include_role: name=lotus_fountain
      when: "'faucet' in group_names"
    - include_role: name=stats
      when: "'stats' in group_names"
    - include_role: name=lotus_pcr
      when: "'pcr' in group_names"

- hosts: scratch
  become: true
  module_defaults:
    package:
      force_apt_get: yes
  tasks:
    - include_role: name=lotus_fullnode
      vars:
        lotus_import_peerkey: true
