---
- hosts: base
  tasks:
    - include_role:
        name: telegraf
    - name: Update repos and install deps
      apt:
        pkg:
          - mesa-opencl-icd
          - ocl-icd-opencl-dev
          - ntp
        update_cache: yes
