---
- hosts: all
  become: yes
  vars:
    lotus_binary_src: "/tmp/lotus"
    logz_inputs:
      - type: log
        paths:
          - /var/log/lotus.log
        fields:
          logzio_codec: json
          token: "{{ logz_io_shared_token }}"
          type: lotus-daemon
        fields_under_root: true
        json.keys_under_root: false
        json.message_key: msg
        encoding: utf-8
        ignore_older: 3h
      - type: log
        paths:
          - /var/log/lotus-miner.log
        fields:
          logzio_codec: json
          token: "{{ logz_io_shared_token }}"
          type: lotus-mine
        fields_under_root: true
        json.keys_under_root: false
        json.message_key: msg
        encoding: utf-8
        ignore_older: 3h
  roles:
    - role: telegraf
    - role: filebeat_logz_io
    - role: lotus-fullnode

