---
- hosts: all
  become: true
  vars:
    ssh_user: "{{ ansible_user }}"
    offboarded_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDVZxq+3H4Nza5YflAK46AdTexQzggXfS4w964qctX459Fbch+trnF534xd2AIQDWZnpONiULf9H02oj0xwyKVajw5T74ESXdukG89S0x+EvxkTIWZyzCdDpomfUttX3Ni29UrJyBevGdzhA4NLSe8H6Jpqb2szh8bllnuZXKK5Z8ulXm13KblfHvQ6Eu+yhJQzAYf6ZQcL5lSbD8Zd/0NUZA1f6e7OBPHBencZXXVjsdVmn+pqUOuEEoNQ6K7lftdByy/XGlVsLn2743ai6BPhw25lugax1ExLV1YJ7n+339SvZ40Z2x7FM+lMlWBVLt/nuwp/GgirIrv/I86vGXNj lanzafame
  tasks:
    - name: Remove from authorized keys
      authorized_key:
        user: "{{ ssh_user }}"
        exclusive: yes
        state: absent 
        key: "{{ item }}"
      loop: "{{ offboarded_keys }}"

