---
- hosts: ceph
  tasks:
    - name: get eth0 interface name
      shell: "ip link | awk '{print $2}' | grep enp | tr -d : | head -1"
      register: eth0
    - debug:
        msg: "{{ eth0.stdout }}"
    - name: 'remove eth0 from bond'
      shell: 'echo "-{{ eth0.stdout }}" > /sys/class/net/bond0/bonding/slaves'
      run_once: False
      ignore_errors: True
    - name: edit network interfaces config
      lineinfile:
        path: /etc/network/interfaces
        regexp: '{{ item.from }}'
        line: '{{ item.to }}'
        state: present
      with_items:
        - { from: 'iface {{ eth0.stdout }} inet manual', to: 'iface {{ eth0.stdout }} inet static'}
        - { from: 'bond-master bond0', to: '    address {{ vlan2_ip }}'}
      run_once: False
      ignore_errors: True
    - name: configure netmask
      lineinfile:
        path: /etc/network/interfaces
        insertafter: '    address {{ vlan2_ip }}'
        line: '    netmask 255.255.255.0'
        firstmatch: yes
    - name: restart eth0
      shell: 'ifdown {{ eth0.stdout }} && sleep 5 && ifup {{ eth0.stdout }}'
      run_once: False
      ignore_errors: True
