# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/disco64"
  config.disksize.size = "16GB"

  # VBox is crazy slow to boot this vm for the first time
  config.vm.boot_timeout = 900
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "vagrant0", primary: true do |node|
    node.vm.hostname = "vagrant0"
    node.vm.network "private_network", ip: "10.10.100.100"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.inventory_path = "vagrant_hosts.yml"
    ansible.playbook = "vagrant.yml"
    ansible.ask_vault_pass = false
  end
end
