# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.disksize.size = "16GB"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./pre-seal", "/vagrant/pre-seal", mount_options: ["uid=532", "gid=532"]

  # VBox is crazy slow to boot this vm for the first time
  config.vm.boot_timeout = 900
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.define "preminer0", primary: true do |node|
    node.vm.hostname = "preminer0"
    node.vm.network "private_network", ip: "10.10.100.100"
  end

  config.vm.define "bootstrap0", primary: true do |node|
    node.vm.hostname = "bootstrap0"
    node.vm.network "private_network", ip: "10.10.100.101"
  end

  config.vm.define "toolshed0", primary: true do |node|
    node.vm.hostname = "toolshed0"
    node.vm.network "private_network", ip: "10.10.100.102"
  end

  config.vm.define "scratch0", primary: true do |node|
    node.vm.hostname = "scratch0"
    node.vm.network "private_network", ip: "10.10.100.103"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.inventory_path = "inventories/vagrant/hosts.yml"
    ansible.playbook = "vagrant.yml"
    ansible.ask_vault_pass = false
  end
end
