# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/disco64"

  # VBox is crazy slow to boot this vm for the first time
  config.vm.boot_timeout = 900
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.vm.define "general", primary: true do |general|
    general.vm.hostname = "vagrant"
    general.vm.network "private_network", ip: "10.10.100.100"
    general.vm.provision "ansible" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.inventory_path = "hosts-vagrant"
      ansible.playbook = "vagrant.yml"
      ansible.limit = "all"
      ansible.ask_vault_pass = false
      ansible.raw_arguments = ["--vault-password-file", "$HOME/.ansible_vault_pass.txt"]
      ansible.extra_vars = {
        ansible_ssh_user: "vagrant",
      }
      ansible.verbose = ""
    end
  end
end
