---
all:
  vars:
    ssh_ops:
      - filecoin
      - cory
      - ognots
      - travisperson
    ssh_lotus:
      - kubuxu
      - magik6k
      - whyrusleeping
      - whysosirius
      - vyzo
      - aayush
    ssh_sentinel:
      - mg
    ssh_general: []
    ssh_all: "{{ ssh_ops + ssh_sentinel + ssh_lotus + ssh_general | unique }}"
  children:
    packet:
      vars:
        ansible_user: root
      children:
        bootstrap0:
          hosts:
            bootstrap-0.testnet.fildev.network:
        bootstrap1:
          hosts:
            bootstrap-1.testnet.fildev.network:

        bootstrap2:
          hosts:
            bootstrap-2.testnet.fildev.network:
        bootstrap3:
          hosts:
            bootstrap-3.testnet.fildev.network:

        bootstrap4:
          hosts:
            bootstrap-4.testnet.fildev.network:
        bootstrap5:
          hosts:
            bootstrap-5.testnet.fildev.network:

    aws:
      vars:
        ansible_user: ubuntu
      children:
        preminer0:
          hosts:
            preminer-0.testnet.fildev.network:
        preminer1:
          hosts:
            preminer-1.testnet.fildev.network:
        preminer2:
          hosts:
            preminer-2.testnet.fildev.network:

        toolshed0:
          hosts:
            toolshed-0.testnet.fildev.network:

        toolshed1:
          hosts:
            toolshed-1.testnet.fildev.network:

        toolshed2:
          hosts:
            toolshed-2.testnet.fildev.network:

        toolshed3:
          hosts:
            toolshed-3.testnet.fildev.network:

        scratch0:
          hosts:
            scratch-0.testnet.fildev.network:
        scratch1:
          hosts:
            scratch-1.testnet.fildev.network:

    t01000:
      children:
        preminer0:

    t01001:
      children:
        preminer1:

    t01002:
      children:
        preminer2:

    lotus_daemon:
      children:
        preminer:
        bootstrap:
        scratch:
        toolbox:

    lotus_miner:
      children:
        t01000:
        t01001:
        t01002:

    toolbox:
      children:
        faucet:
        stats:
        chainwatch:
        pcr:

    ####

    faucet:
      vars:
        ssh_keys_access: "{{ ssh_ops }}"
      children:
        toolshed0:

    stats:
      vars:
        ssh_keys_access: "{{ ssh_ops }}"
      children:
        toolshed2:

    chainwatch:
      vars:
        ssh_keys_access: "{{ ssh_ops + ssh_lotus + ssh_sentinel | unique }}"
      children:
        toolshed3:

    pcr:
      vars:
        ssh_keys_access: "{{ ssh_ops }}"
      children:
        toolshed1:

    preminer:
      vars:
        ssh_keys_access: "{{ ssh_ops }}"
      children:
        t01000:
        t01001:
        t01002:

    bootstrap:
      vars:
        ssh_keys_access: "{{ ssh_ops + ssh_lotus | unique }}"
      children:
        bootstrap0:
        bootstrap1:
        bootstrap2:
        bootstrap3:
        bootstrap4:
        bootstrap5:

    scratch:
      vars:
        ssh_keys_access: "{{ ssh_all | unique }}"
      children:
        scratch0:
        scratch1:
