lotus_miner_presealed: "yes"
lotus_miner_systemd_extras:
  LimitNOFILE: 32768
  LimitNOFILESoft: 24576

lotus_miner_verified_deals: true
lotus_miner_data_root: "/fildev-network"

lotus_miner_presealed_sectors:
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/000"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/032"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/064"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/096"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/128"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/160"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/192"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/224"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/256"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/288"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/320"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/352"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/384"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/416"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/448"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/480"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/512"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/544"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/576"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/608"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/640"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/672"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/704"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/736"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/768"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/800"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/832"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/864"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/896"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/928"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/960"
  - "{{ lotus_miner_data_root }}/pre-seal/{{ proof_type }}/{{ proof_version }}/{{ sector_size }}/{{ lotus_miner_addr }}/992"
