---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: mainnet-lotus
  namespace: ntwk-mainnet
spec:
  interval: 5m
  image: docker.io/filecoin/lotus-all-in-one
---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
  name: mainnet-lotus
  namespace: ntwk-mainnet
spec:
  policy:
    semver:
      range: '~1.18.x'
  imageRepositoryRef:
    name: mainnet-lotus
