---
name: build-lotus-container
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      ref:
        description: lotus ref
        required: true
        default: master
      repo:
        description: docker repo
        required: true
        default: travisperson

jobs:
  build-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        network:
          - mainnet
          - nerpanet
          - butterflynet
          - calibnet
    steps:
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout lotus-infra
        uses: actions/checkout@v2
      - name: prepare lotus staging area
        run: mkdir _source
      - name: Checkout Lotus (nightly)
        if: ${{ github.event_name == 'schedule' }}
        uses: actions/checkout@v2
        with:
          repository: filecoin-project/lotus
          path: _source/lotus
      - name: Checkout Lotus (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/checkout@v2
        with:
          repository: filecoin-project/lotus
          ref: ${{ github.event.inputs.ref }}
          path: _source/lotus
      - name: Checkout Lotus (dispatch)
        if: ${{ github.event_name == 'repository_dispatch' }}
        uses: actions/checkout@v2
        with:
          repository: filecoin-project/lotus
          ref: ${{ github.event.client_payload.ref }}
          path: _source/lotus
      - name: build containers (nightly)
        if: ${{ github.event_name == 'schedule' }}
        run: ./scripts/build_containers.bash --src _source/lotus --network ${{ matrix.network }} --repo coryschwartz --docker-tag nightly
      - name: build containers (manual)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: ./scripts/build_containers.bash --src _source/lotus --network ${{ matrix.network }} --repo ${{ github.event.inputs.repo }} --tag ${{ github.event.inputs.ref }}
      - name: build containers (dispatch)
        if: ${{ github.event_name == 'repository_dispatch' }}
        run: ./scripts/build_containers.bash --src _source/lotus --network ${{ matrix.network }} --repo ${{ github.event.client_payload.repo }} --tag ${{ github.event.client_payload.tag }}

