name: Flux-image-updates PR auto merge
on:
  pull_request:
    types:
      - opened
    branches:
      - releases/flux-image-updates
jobs:
  pull-request:
    name: Auto merge flux PRs
    runs-on: ubuntu-latest
    - name: automerge
      uses: pascalgn/automerge-action@v0.15.5
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "flux-image-automation,automerge"
        MERGE_FILTER_AUTHOR: fil-infra-bot
        # This retry config allows time for merge checks to run
        MERGE_RETRY_SLEEP: 10000 # 10s in milliseconds
        MERGE_RETRIES: 6
