name: Flux-image-updates auto PR
on:
  push:
    branches:
    - releases/flux-image-updates

jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      id: open-pr
      name: pull-request
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: |
          🐳 Auto image update
        pr_draft: false
        pr_label: "flux-image-automation,automerge"
        github_token: ${{ secrets.GITHUB_TOKEN }}

    # This won't work for `create` events so we have to listen
    # for branch pushes
    - name: automerge
      needs: pull-request
      uses: pascalgn/automerge-action@v0.15.5
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: "flux-image-automation,automerge"
        MERGE_FILTER_AUTHOR: fil-infra-bot
        # This retry config allows time for merge checks to run
        MERGE_RETRY_SLEEP: 10000 # 10s in milliseconds
        MERGE_RETRIES: 6
        PULL_REQUEST: ${{steps.open-pr.outputs.pr_number}}
