name: Flux-image-updates auto Auto-PR
on:
  create:
    branches: ['flux-image-updates']

jobs:
  pull-request:
    name: Open PR to master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: checkout

    - uses: repo-sync/pull-request@v2
      name: pull-request
      with:
        destination_branch: "master"
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: |
          🐳 Auto image update
        pr_draft: false
        pr_label: "flux-image-automation"
        github_token: ${{ secrets.GITHUB_TOKEN }}
