name: Lotus Ansible Reset Careful

on:
  workflow_dispatch:
    inputs:
      network:
        description: "Network:"
        default: "butterflynet"
        type: choice
        options:
          - butterflynet
      lotus_ref:
        description: "Lotus git ref:"
        default: "master"
      dry-run:
        description: "Dry-run changes"
        type: boolean
        default: true
      verbose:
        description: "Verbose ansible output"
        type: boolean
        default: false

jobs:
  check:
    runs-on: [ self-hosted, linux, x64, 2xlarge ]
    timeout-minutes: 60
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lotus Ansible Prepare
        uses: ./.github/actions/lotus-ansible-prepare
        with:
          branch: ${{ inputs.lotus_ref }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          PRIVATE_SSH_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          ANSIBLE_VAULT_PASSWORD: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}

      - name: Lotus Ansible Reset
        uses: ./.github/actions/lotus-ansible-reset
        with:
          network: ${{ inputs.network }}
          preseal: "true"
          create_cert: "true"
          reset: "true"
          delay: "0"
          check: ${{ inputs.dry-run }}
          verbose: ${{ inputs.verbose }}
