---
name: trigger-lotus-release-automation
on:
  workflow_dispatch:
    inputs:
      release:
        description: "lotus release tag"

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        uses: promiseofcake/circleci-trigger-action@v1
        with:
          user-token: ${{ secrets.CIRCLE_TOKEN }}
          project-slug: filecoin-project/lotus-infra
          branch: master
          payload: |
            {
              "api_workflow_requested": "api-lotus-release-automation",
              "release": "${{ github.event.inputs.release }}"
            }
