apiVersion: v1
kind: Pod
metadata:
  name: debug-worker-pod
  labels:
    app: debug-worker
spec:
  hostNetwork: true
  nodeSelector:
    kubernetes.io/hostname: storage-miner-seal-worker-0
  tolerations:
    - key: "role"
      operator: "Equal"
      value: "lotus-seal-worker"
      effect: "NoSchedule"

  containers:
  - name: debug-worker-container
    image: stongo/lotus:worker 
    command: [sh, -c, tail -f /dev/null]
    securityContext:
      privileged: true     
    env: 
      - name: FIL_PROOFS_PARAMETER_CACHE
        value: /proof-params
    volumeMounts:
      - name: proof-params
        mountPath: /proof-params
      - name: bench
        mountPath: /bench
      - name: swap
        mountPath: /swap
  volumes:
    - name: proof-params
      persistentVolumeClaim:
        claimName: proof-params-pvc
        readOnly: false
    - name: bench
      persistentVolumeClaim:
        claimName: bench-es-pvc 
        readOnly: false
    - name: swap
      hostPath:
        path: /mnt/swap
        
