secrets:
  jwt:
    enabled: true
    secretName: lightweight-snapshot-node-jwt-secret
daemonConfig: |
  [API]
    ListenAddress = "/ip4/0.0.0.0/tcp/1234/http"
  [Libp2p]
    ListenAddresses = ["/ip4/0.0.0.0/tcp/1347"]
  [Chainstore]
    EnableSplitstore = false
